### ISSUE TITLE
License problem?

### ISSUE THREAD

**Issue by uweschaefer** [StephanPraetsch/dockers#1]
IANAL, but there was a discussion quite some months ago, if doing stuff like this is a license violation.
https://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/

**Comment by StephanPraetsch** [comment]
if i understand that blog post correctly then only the users of a docker image with oracle's jdk are breaking the law. not the provider.
nevertheless IANAL neither, i replaced it with openjdk.
